window.TESOURA_SUPABASE_URL = "https://xuplzpispukvtggjasxx.supabase.co";
window.TESOURA_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1cGx6cGlzcHVrdnRnZ2phc3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ5NTI2MjcsImV4cCI6MjA4MDUyODYyN30.aae__P90u3KM1Rr_ESJpJ4JigLnmCmJnhUsyxNA54pw";
